spring:
  # 开发环境数据源配置与ShardingSphere配置兼容
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  
  # ShardingSphere多数据源配置
  shardingsphere:
    datasource:
        names: ds0,ds1
        # Druid连接池公共配置
        common:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          initial-size: 10
          min-idle: 10
          max-active: 50
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          filters: stat,wall,slf4j
          connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=3000
        ds0:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.21.1.55:3324/pbs?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&connectionTimeZone=LOCAL
          username: pbs
          password: pbs
        ds1:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.21.1.55:3324/settledb_dev?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&connectionTimeZone=LOCAL
          username: opt_settle
          password: opt_settle
    sharding:
      default-data-source-name: ds0
      tables:
        # PBS数据库中的号码资源表（分片表）
        number_resource:
          actual-data-nodes: ds0.number_resource_${['139','177','138','136','135','134','150','151','152','153','155','156','157','158','159','180','181','182','183','184','185','186','187','188','189']}
          table-strategy:
            standard:
              range-algorithm-class-name: com.nsrs.framework.sharding.MsisdnPrefixShardingAlgorithm
              precise-algorithm-class-name: com.nsrs.framework.sharding.MsisdnPrefixShardingAlgorithm
              sharding-column: number
        # 结算数据库中的账单表（示例：指定使用ds1数据源）
        settle_bill:
          actual-data-nodes: ds1.settle_bill
        # SIM卡分表配置
        sim_card:
          actual-data-nodes: ds0.sim_card_${0..9}
          table-strategy:
            inline:
              sharding-column: iccid
              algorithm-expression: sim_card_${iccid.substring(iccid.length()-3).toInteger() % 10}
        # IMSI资源分表配置
        imsi_resource:
          actual-data-nodes: ds0.imsi_resource_${0..9}
          table-strategy:
            inline:
              sharding-column: imsi
              algorithm-expression: imsi_resource_${imsi.substring(imsi.length()-2).toInteger() % 10}
        # 绑定关系分表配置
        number_imsi_binding:
          actual-data-nodes: ds0.number_imsi_binding_${['139','177','138','136','135','134','150','151','152','153','155','156','157','158','159','180','181','182','183','184','185','186','187','188','189']}
          table-strategy:
            standard:
              range-algorithm-class-name: com.nsrs.framework.sharding.NumberImsiBindingShardingAlgorithm
              precise-algorithm-class-name: com.nsrs.framework.sharding.NumberImsiBindingShardingAlgorithm
              sharding-column: number
        batch_binding_task:
          actual-data-nodes: ds1.batch_binding_task
    props:
      sql:
        show: true

  redis:
    cluster:
      nodes: 10.21.1.203:7001,10.21.1.203:7002,10.21.1.203:7003,10.21.1.203:7004,10.21.1.203:7005,10.21.1.203:7006
      max-redirects: 6
    timeout: 30000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 200
        min-idle: 20
# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,env  # 暴露健康检查、应用信息和环境信息端点（移除metrics避免与ShardingSphere冲突）
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: false  # 禁用数据库健康检查，避免ShardingSphere isValid方法不支持的问题

# Knife4j配置 - 统一API文档
knife4j:
  enable: true
  production: false
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    language: zh-CN
    enableSwaggerModels: false
    enableDocumentManage: false
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableAfterScript: false
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: false
    enableRequestCache: false
    enableHost: false
    enableHostText: http://localhost:8088
    enableHomeCustom: false
    homeCustomLocation: classpath:doc/home.md
    enableSearch: false
    enableFooter: false
    enableFooterCustom: false
    footerCustomContent: Copyright © 2023 NSRS系统

# 日志配置
logging:
  level:
    com.nsrs: debug
    com.nsrs.busacc.grpc: debug  # GRPC服务日志
    org.apache.shardingsphere: debug
    io.grpc: info  # GRPC框架日志
    net.devh.boot.grpc: debug  # GRPC Spring Boot集成日志
    io.lettuce: warn  # Redis客户端日志级别，避免过多调试信息
    io.lettuce.core: warn  # Lettuce核心组件日志级别
    io.netty: warn  # Netty网络框架日志级别

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.nsrs.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# GRPC服务配置
grpc:
  server:
    port: 9090
    enable-reflection: true
    enable-health-service: true
    max-inbound-message-size: 4MB
    max-inbound-metadata-size: 8KB

# 系统配置
nsrs:
  # 库存告警缓存配置
  inventory:
    cache:
      # 缓存类型：memory（内存缓存）或 redis（Redis共享缓存）
      type: memory
      # 缓存过期时间（分钟）
      expire-time: 5
      # 是否启用缓存
      enabled: true

  # 选卡选号配置
  number-selection:
    # 随机号码池大小
    pool-size: 30
    # 是否启用选号功能
    enabled: true
  
  # SIM卡选择功能配置
  sim-card-selection:
    enabled: true  # 是否启用SIM卡选择功能
    pool-size: 30  # 随机SIM卡池大小
    allowed-statuses: [1]  # 允许的SIM卡状态，1-空闲
    max-sharding-tables: 10  # 最大查询分表数量

  auth:
    enabled: true  # 开发环境启用内置权限
  sharding:
    # 开发环境可以设置更短的配置重载间隔，便于测试
    reload-interval: 60

  # 文件配置
  file:
    # 文件上传路径
    upload:
      path: /upload/
    # 模板文件路径
    template:
      path: /templates/