apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: nsrs
  labels:
    app: mysql
data:
  # MySQL 配置文件
  my.cnf: |
    [mysqld]
    # 基本配置
    port = 3306
    bind-address = 0.0.0.0
    
    # 字符集配置
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    init-connect = 'SET NAMES utf8mb4'
    
    # 连接配置
    max_connections = 200
    max_connect_errors = 1000
    
    # 缓冲区配置
    innodb_buffer_pool_size = 512M
    innodb_log_file_size = 128M
    innodb_log_buffer_size = 16M
    
    # 查询缓存
    query_cache_type = 1
    query_cache_size = 64M
    
    # 慢查询日志
    slow_query_log = 1
    slow_query_log_file = /var/log/mysql/slow.log
    long_query_time = 2
    
    # 错误日志
    log-error = /var/log/mysql/error.log
    
    # 二进制日志
    log-bin = mysql-bin
    binlog_format = ROW
    expire_logs_days = 7
    
    # InnoDB 配置
    innodb_file_per_table = 1
    innodb_flush_log_at_trx_commit = 2
    innodb_flush_method = O_DIRECT
    
    # 时区设置
    default-time-zone = '+08:00'
    
    [mysql]
    default-character-set = utf8mb4
    
    [client]
    default-character-set = utf8mb4
  
  # 初始化数据库脚本
  init.sql: |
    -- 创建 NSRS 数据库
    CREATE DATABASE IF NOT EXISTS nsrs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    
    -- 创建应用用户
    CREATE USER IF NOT EXISTS 'nsrs'@'%' IDENTIFIED BY 'nsrs123';
    GRANT ALL PRIVILEGES ON nsrs.* TO 'nsrs'@'%';
    
    -- 刷新权限
    FLUSH PRIVILEGES;
    
    -- 使用 nsrs 数据库
    USE nsrs;
    
    -- 这里可以添加初始化表结构的 SQL
    -- 由于应用使用 JPA 自动创建表，这里暂时留空
    -- 如果需要预置数据，可以在这里添加 INSERT 语句